### ISSUE TITLE
How to make trait_file  from GWAS summary statistics ?

### ISSUE THREAD

**Issue by dmsalsgh97** [sankaranlab/SCAVENGE#3]
Hello,
First, thanks for developing a new method for overcoming the data sparsity of scATAC! 
We were suffering the same issue...

My pipeline is using archR and I successfully exported peakmatrix and import it to SCAVENGE.
I have 2 questions for running SCAVENGE on my sample.

1. my archR object is made using hg38, so my peakmatrix is hg38 mapped. 
 If I liftover GWAS SNPs from hg19 to hg38, is it possible to run SCAVENGE on my hg38 mapped peakmatrix?

2. I'm trying to generate trait_file from GWAS summary statistics file which I want to use. 
   I understood that to run SCAVENGE, I have to calculate each GWAS SNP's posterior probability of causality.

![image](https://user-images.githubusercontent.com/42495757/167331279-2e601892-a0ee-4106-a045-9420c3feb0c6.png)
I tried to find how to generate trait_file from GWAS summary statistics file, but I couldn't find it...
So, is there any instructions for it?

Thanks.

**Comment by fl-yu** [comment]
Hi Thank you for your interest in our tool!

1. yes it is definitely good to run SCAVENGE if you liftover GWAS SNPs from hg19 to hg38
2. Correct, you need to generate fine-mapped data from GWAS by using software such as FINEMAP http://www.christianbenner.com/ that is what we used in the paper. 

For a detailed procedure of fine-mapping, you may also follow these two papers of [BCX2](https://www.cell.com/cell/pdf/S0092-8674(20)30999-5.pdf) and [NG paper](https://www.nature.com/articles/s41588-019-0362-6). I am sure there will be some affiliated code that may be useful.

**Comment by dmsalsgh97** [comment]
Thanks for reply!
I'll try this. 

Thanks.

**Comment by twoneu** [comment]
@dmsalsgh97, did you ever find a good solution for this? I am also interested in calculating posterior probabilities from a GWAS summary statistic file.

**Comment by fl-yu** [comment]
Hi Guys! Thanks to our fine-mapping expert Liam Cato, we added a [**wiki page**](https://github.com/sankaranlab/SCAVENGE/wiki) for a tutorial of fine mapping data processing from GWAS summary statistics. Please let us know if you have any questions!

**Comment by dmsalsgh97** [comment]
I successfully followed your detailed instructions on the wiki page and the result seems reasonable to me!
I appreciate your team's help.

I have a question about analyzing my GWAS-associated trait...
My GWAS-associated trait is numeric and directional. So, If the trait's value goes down, then it occurs disease.

I have a case-control snATAC-seq dataset for the related disease, and I want to know if the diseased cells have different TRS score than normal cells.

In this case, 
1. Can I divide my clusters by case-control (like clusterA_Dis, clusterA_Normal, etc.) and adopt SCAVENGE method separately? 
2. And If possible, TRS score is suitable for statistics like t-test?

Sorry for the user-specific question, But it will be really nice!

Thanks.

**Comment by fl-yu** [comment]
Hi Glad to see it works!!
Also great to see that you are able to perform the analysis successfully and it looks beautiful. To answer your questions:

1. yes for sure, you can take advantage of the annotation info of your data to perform an in-depth analysis
2. definitely, I would also suggest you follow up on our paper, especially for the covid19 section where you can take it as a potential model for your specific analysis. btw it is kind of surprising to me that the TRSs are higher in the disease-condition clusters compared to those of normal ones:)

Please let me know if you have any questions but it would be great if you can open new discussions/issues if the questions are on the new topic. Thanks!
