### ISSUE TITLE
error at get_sigcell_simple()

### ISSUE THREAD

**Issue by AnjaliC4** [sankaranlab/SCAVENGE#9]
Hi, thanks for this great tool! I am facing an error during permutation analysis:

Stationary step: 74
Stationary Delta: 9.83820972996253e-06
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
  arguments imply differing number of rows: 0, 199764
Calls: get_sigcell_simple ... as.data.frame -> as.data.frame.list -> do.call -> <Anonymous>

**Comment by AnjaliC4** [comment]
Hi, following up to see if you guys had any suggestions to resolve this error. Thanks

**Comment by fl-yu** [comment]
Hi, sorry for the late reply! I have no idea about this error, can you post more information about your data and output? Thank you!

**Comment by AnjaliC4** [comment]
Hi, I used ~3000 fine-mapped SNPs as input and here is the RSE object with peak count matrix. TRS gets calculated successfully but not the permutation step. 
class: RangedSummarizedExperiment 
dim: 6 200071 
metadata(0):
assays(1): counts
rownames: NULL
rowData names(2): bias idx
colnames(200071): atac_A1B1#CACCACTTCCAGGTAT-1
  atac_A1B1#GTAGGAGTCCGGGCAT-1 ... atac_A28B28#TGCTATTAGAGTGGTC-1
  atac_A28B28#CCTTGCATCGCAAGCC-1
colData names(123): orig.ident nCount_peaks ... nCount_RNA nFeature_RNA

<img width="1438" alt="Screen Shot 2022-12-03 at 3 58 03 PM" src="https://user-images.githubusercontent.com/60046859/205461835-37d1ed29-e679-40d2-b549-4dfe38eacf02.png">
<img width="922" alt="Screen Shot 2022-12-03 at 3 59 02 PM" src="https://user-images.githubusercontent.com/60046859/205461870-3e9fa209-5eb0-444b-81d3-a6ade4850220.png">

**Comment by fl-yu** [comment]
Thank you for the info.
I figure the discrepancy is not the cause of this error if your input for the dimension of `knn_sparse_mat` and length of `topseed_npscore` matched. I noticed that in your previous error there is a number of 199764 that should be the number related to the permutation output, which is different than the number of your input 199779. I think this could be the key. Can you post the entire error message of this analysis? thank you!

**Comment by AnjaliC4** [comment]
1000
Stationary step: 80
Stationary Delta: 9.63450666772587e-06
Stationary step: 81
Stationary Delta: 9.48843841608067e-06
Stationary step: 74
Stationary Delta: 9.99591098634589e-06
Stationary step: 74
Stationary Delta: 9.44719369263237e-06
Stationary step: 74
Stationary Delta: 9.4838064933629e-06
Stationary step: 75
Stationary Delta: 9.79173786751816e-06
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
  arguments imply differing number of rows: 0, 199845
Calls: get_sigcell_simple ... as.data.frame -> as.data.frame.list -> do.call -> <Anonymous>
In addition: Warning message:
In mclapply(1:permutation_times, mc.cores = mycores, function(i) { :
  scheduled cores 1, 2, 3 did not deliver results, all values of the jobs will be affected
Execution halted
slurmstepd: error: Detected 3 oom-kill event(s) in StepId=1237064.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by fl-yu** [comment]
It seems that a out-of-memory issue, can you increase the memory of each core or use one core to process? Also, can you post how it goes with just 100 times permutation for 1 core and 4 cores, respectively?

**Comment by AnjaliC4** [comment]
Hi, this was resolved with 5 cores and more memory!
Thanks
